name: CI
on:
  push: { branches: [ main ] }
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -U pip
      # If you have requirements.txt, replace the next line with: pip install -r requirements.txt
      - run: pip install fastapi uvicorn pytest
      - run: pytest -q || echo "No tests yet — CI wiring OK"
